accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from accountapp.views import UserCreateView, UserDetailView, CustomLoginView, CustomLogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
]

miniProject/urls.py
from django.contrib import admin
from django.urls import path
# 2개의 앱을 할 때는 이렇게 as로 별명짓듯이 함
from accountapp import views as account
from boardapp import views as board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', account.main, name = 'main-page'),
    path('sign/', account.signup, name = 'sign-up'),
    path('board/', board.board_main, name = 'board-main'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/',ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.
class account(models.Model):
    Username = models.CharField(max_length=64, verbose_name="사용자 계정")

    password = models.CharField(max_length=64, verbose_name="비밀번호")
    # 아래거는 utc 시간으로만 기록이 되네
    registered_dttm = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")

    class Meta:
        db_table = 'account_user'

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from accountapp.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username','password1','password2','company','phone_number','telecom', 'aws_access_key', 'aws_secret_key']
        widgets = {
            'aws_secret_key' : forms.PasswordInput(),
        }

accountapp/views.py
from django.shortcuts import render
import bcrypt
from .models import account
def main(request):
    #이걸 로그인 되게 만들어야 함
    #로그인 페이지 받아옴
    if request.method == 'GET':
     return render(request, 'main.html')
    elif request.method == 'POST':
        # 이 것을 가지고 메시지를 나오게 할 수 있음
        res_data = {}
        # db user 테이블
        get_user = account()

        # user , 비밀번호 가져옴
        Username = request.POST.get('Username', None)
        wcpassword = request.POST.get('password', None)
        if Username and wcpassword :
              try:
                  # db를 지정해주니까 갈 수 있는듯
                  User =  account.objects.get(Username = Username)
              #일치 하지 않을 때 항목
              except account.DoesNotExist:

               res_data['error'] = '사용자 아이디가 없음'
                #return을 해줘야 페이지가 보임
               return render(request, "main.html", res_data)


              if not bcrypt.checkpw(wcpassword.encode('utf-8'), User.password.encode("utf-8")):
                   res_data['error'] = '사용자 비밀번호가 틀림'
              else:
                   res_data['error'] = '로그인 성공'
              return render(request, "main.html", res_data)
# Create your views here.
def signup(request):
    # 그냥 페이지 불러 오는듯
    if request.method == 'GET':
        return render(request, 'signup.html')
    # 여기부터 회원 가입 데이터를 쌓는거
    elif request.method == 'POST':
        # 이 것을 가지고 메시지를 나오게 할 수 있음
        res_data = {}
        # account db 변수 설정?
        new_user = account()
        # 요청을 가져옴
        new_user.Username = request.POST.get('Username', None)
        wcpassword1 = request.POST.get('password1', None)
        wcpassword2 = request.POST.get('password2', None)
        #비밀번호 불일치 할 때
        if wcpassword1 != wcpassword2:
            res_data['error'] = '비밀번호 불일치'

        else:
            # 암호 해쉬 화 .decode를 붙여야 나중에 로그인시 invaild salt를 피함
            hashed_password = bcrypt.hashpw(wcpassword1.encode("utf-8"), bcrypt.gensalt()).decode('utf-8')
            # 암호 변수 저장
            new_user.password = hashed_password
            # 이게 저장 하는 것을 의미
            new_user.save()
            # res_data가 있어야 쌓이는듯?
        return render(request, 'signup.html', res_data)

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:30%; margin:0 auto;">
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign Up</button>
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="background-color:pink;">
        <div class="profile_img" style="padding-top:2rem; margin: 4rem auto; text-align:center;">
            <img src="{{ target_user.profile.image.url }}" alt="" style="height: 10rem; width: 10rem; border-radius: 20rem; margin-bottom: 2rem;"/>
            <p style="position:relative; bottom:1rem; font-family: 'Titillium Web', sans-serif;">{{ target_user.profile.nickname }}</p>
            <p style="position:relative; bottom:1rem; font-family: 'Titillium Web', sans-serif;">{{ target_user.profile.message }}</p>
            <a class="btn btn-outline-primary" href="{% url 'profileapp:update' pk=target_user.profile.pk %}">Update</a>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="container" style="text-align:center; width:20rem;">
        <div class="login_form" style="padding-top:73%;">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-outline-primary">Sign In</button>
            </form>
        </div>
    </div>
{% endblock %}