accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from accountapp.views import UserCreateView, UserDetailView, CustomLoginView, CustomLogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
]

miniProject/urls.py
from django.contrib import admin
from django.urls import path
# 2개의 앱을 할 때는 이렇게 as로 별명짓듯이 함
from accountapp import views as account
from boardapp import views as board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', account.main, name = 'main-page'),
    path('sign/', account.signup, name = 'sign-up'),
    path('board/', board.board_main, name = 'board-main'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}



    {% block content %}
    {% endblock %}




    {% include 'footer.html' %}


</body>
</html>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>miniProject</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="{% static 'base.css' %}" rel="stylesheet" type="text/css"/>

    {#    GOOGLE FONT#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300&display=swap" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">MiniProject</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% if user.is_authenticated %}
                {% if request.resolver_match.url_name == 'detail' %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'accountapp:detail' pk=user.pk %}">My Page <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="margin-right:.3rem;">Search</button>
        </form>

        {% if user.is_authenticated %}
            <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'accountapp:logout' %}" class="form-inline">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="text-decoration:none;">Sign Out</button>
            </form>
        {% else %}
            {% if request.resolver_match.url_name == 'login' %}
                <form method="post" action="{% url 'accountapp:create' %}" class="form-inline">
                    {% csrf_token %}
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="text-decoration:none;">Sign Up</button>
                </form>
            {% else %}
                <form method="post" action="{% url 'accountapp:create' %}" class="form-inline">
                    {% csrf_token %}
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="text-decoration:none;">
                        <a href="{% url 'home' %}" style="text-decoration:none; color:inherit;">Home</a>
                    </button>
                </form>
            {% endif %}
        {% endif %}
    </div>
</nav>

templates/main.html
{% extends 'base.html' %}