accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from accountapp.views import UserCreateView, UserDetailView, CustomLoginView, CustomLogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView

app_name = 'articleapp'

urlpatterns = [
    path('list/',TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/',ArticleCreateView.as_view(), name='create')
]

miniProject/urls.py
from django.contrib import admin
from django.urls import path
# 2개의 앱을 할 때는 이렇게 as로 별명짓듯이 함
from accountapp import views as account
from boardapp import views as board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', account.main, name = 'main-page'),
    path('sign/', account.signup, name = 'sign-up'),
    path('board/', board.board_main, name = 'board-main'),
]

articleapp/models.py
from django.db import models

from accountapp.models import CustomUser


# Create your models here.
# writer title image content created_at

class Article(models.Model):
    writer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, related_name='article')
    title = models.CharField(max_length=20, null=False)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)
    create_at = models.DateTimeField(auto_now_add=True)

articleapp/forms.py
from django import forms
from django.forms import ModelForm
from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']
        widgets = {
            'image': forms.ClearableFileInput(attrs={'multiple': False}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].required = False

articleapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


# Create your views here.

class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/create.html'

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:30%; margin:0 auto;">
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Post</button>
        </form>
    </div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <style>
        .container div {
            width: 250px;
            background-color: antiquewhite;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
        }

        .container img{
            width:100%;
            border-radius: 1rem;
        }

    </style>
    <div class="container">
        <div class="item1">
            <img src="https://picsum.photos/200/300" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/310" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/320" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/330" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/340" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/350" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/360" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/370" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/380" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/390" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/400" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/410" alt=""/>
        </div>
        <div class="item1">
            <img src="https://picsum.photos/200/420" alt=""/>
        </div>

    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
{% endblock %}