accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from accountapp.views import UserCreateView, UserDetailView, CustomLoginView, CustomLogoutView

app_name = 'accountapp'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
]

miniProject/urls.py
from django.contrib import admin
from django.urls import path
# 2개의 앱을 할 때는 이렇게 as로 별명짓듯이 함
from accountapp import views as account
from boardapp import views as board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', account.main, name = 'main-page'),
    path('sign/', account.signup, name = 'sign-up'),
    path('board/', board.board_main, name = 'board-main'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/',ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(), name='update'),
]

profileapp/models.py
from django.db import models

from accountapp.models import CustomUser


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    nickname = models.CharField(max_length=15, unique=True, null=False, blank=False)
    image = models.ImageField(upload_to='profile/', null=True)
    message = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'user_profile'
        verbose_name_plural = 'user_profile_group'

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image','nickname','message']

profileapp/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


# Create your views here.

class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        add_profile = form.save(commit=False)
        add_profile.user = self.request.user
        add_profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)



class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        user = self.object.user
        if not user == request.user:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:30%; margin:0 auto;">
        <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:30%; margin:0 auto;">
        <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}